apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-rest 
spec:
  selector:
    matchLabels:
      app: flask-rest
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-rest
    spec:
      containers:
      - name: flask-rest 
        image: flask-rest:dev
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: dev-flask-rest-service
spec:
  ports:
  - port: 8101
    targetPort: 8100
    protocol: TCP
  selector:
    app: flask-rest
  type: LoadBalancer
