apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-rest 
spec:
  selector:
    matchLabels:
      app: flask-rest
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-rest
    spec:
      containers:
      - name: flask-rest 
        image: flask-rest-qa:latest
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8200
---
apiVersion: v1
kind: Service
metadata:
  name: qa-flask-rest-service
spec:
  ports:
  - port: 8201
    targetPort: 8200
    protocol: TCP
  selector:
    app: flask-rest
  type: LoadBalancer
